dataset: GOODCMNIST-concept
num_workers: 4
model:
  name: GraphMLPMixer
  gnn_type: GINEConv
  nlayer_gnn: 4
  nlayer_mlpmixer: 4
train:
  runs: 1
  lr_patience: 50
  epochs: 1
metis:
  n_patches: 32
pos_enc:
  lap_dim: 8